"use client";

import { LEAD_STATUSES, STATUS_STYLES } from "@/lib/constants";
import { Building2, Mail, MessageCircle, Pencil, Phone, Plus, Search, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";

type Service = { id: number; name: string };
type Message = { id: number; role: string; content: string; createdAt: string };
type Lead = { id: number; name: string; phone: string; email: string | null; company: string | null; status: string; budget: number | null; estimatedValue: number | null; source: string | null; notes: string | null; aiSummary: string | null; serviceId: number | null; service: Service | null; updatedAt: string; conversation?: { messages: Message[] } | null };

const empty = { name: "", phone: "", email: "", company: "", status: "Nuevo", budget: "", estimatedValue: "", source: "WhatsApp", notes: "", serviceId: "" };
const input = "w-full rounded-xl border border-[#dedbe6] bg-white px-3.5 py-2.5 text-sm outline-none transition focus:border-violet-500 focus:ring-3 focus:ring-violet-100";
const money = (value: number) => `$${Math.round(value).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`;
const shortDate = (value: string) => {
  const parts = new Intl.DateTimeFormat("en-CA", { year: "numeric", month: "2-digit", day: "2-digit", timeZone: "America/Guatemala" }).formatToParts(new Date(value));
  return `${parts.find(part => part.type === "day")?.value}/${parts.find(part => part.type === "month")?.value}/${parts.find(part => part.type === "year")?.value}`;
};

export function LeadsManager({ initialLeads, services }: { initialLeads: Lead[]; services: Service[] }) {
  const [leads, setLeads] = useState(initialLeads); const [query, setQuery] = useState("");
  const [editing, setEditing] = useState<Lead | null>(null); const [viewing, setViewing] = useState<Lead | null>(null); const [creating, setCreating] = useState(false);
  const [form, setForm] = useState<Record<string, string>>(empty); const [error, setError] = useState("");
  const filtered = useMemo(() => leads.filter(l => `${l.name} ${l.company} ${l.email}`.toLowerCase().includes(query.toLowerCase())), [leads, query]);
  async function reload() { const data = await fetch("/api/leads").then(r => r.json()); setLeads(data); return data as Lead[]; }
  function openCreate() { setForm(empty); setEditing(null); setCreating(true); setError(""); }
  function openEdit(lead: Lead) { setEditing(lead); setForm({ name: lead.name, phone: lead.phone, email: lead.email || "", company: lead.company || "", status: lead.status, budget: lead.budget?.toString() || "", estimatedValue: lead.estimatedValue?.toString() || "", source: lead.source || "", notes: lead.notes || "", serviceId: lead.serviceId?.toString() || "" }); setCreating(true); setViewing(null); setError(""); }
  async function save(e: { preventDefault(): void }) { e.preventDefault(); const res = await fetch(editing ? `/api/leads/${editing.id}` : "/api/leads", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await res.json(); if (!res.ok) return setError(data.error); await reload(); setCreating(false); }
  async function quickStatus(id: number, status: string) { await fetch(`/api/leads/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); await reload(); }
  async function remove(id: number) { if (!confirm("¿Eliminar este prospecto y su conversación?")) return; await fetch(`/api/leads/${id}`, { method: "DELETE" }); setViewing(null); await reload(); }
  return <div className="mx-auto max-w-[1400px]">
    <header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-sm font-medium text-violet-600">Pipeline comercial</p><h1 className="text-3xl font-bold tracking-tight">Prospectos</h1><p className="mt-2 text-sm text-[#777481]">Administra tus oportunidades desde el primer contacto hasta el cierre.</p></div><button onClick={openCreate} className="flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-medium text-white shadow-sm hover:bg-violet-700"><Plus size={17}/> Nuevo prospecto</button></header>
    <div className="mb-4 flex max-w-sm items-center gap-2 rounded-xl border border-[#e4e1e9] bg-white px-3"><Search size={17} className="text-[#8d8995]"/><input aria-label="Buscar prospectos" value={query} onChange={e => setQuery(e.target.value)} className="w-full bg-transparent py-2.5 text-sm outline-none" placeholder="Buscar por nombre, empresa o email..."/></div>
    <section className="overflow-hidden rounded-2xl border border-[#ebe9f0] bg-white shadow-[0_4px_18px_rgba(32,29,53,.035)]"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-[#faf9fc] text-xs uppercase tracking-wide text-[#8a8792]"><tr>{["Prospecto", "Contacto", "Servicio", "Estado", "Presupuesto", "Valor", "Último contacto", ""].map(h => <th key={h} className="px-5 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{filtered.map(lead => <tr key={lead.id} className="border-t border-[#f0eef3] hover:bg-[#fcfbfd]"><td className="px-5 py-4"><button aria-label={`Ver detalle de ${lead.name}`} onClick={() => setViewing(lead)} className="text-left"><span className="block font-semibold">{lead.name}</span><span className="text-xs text-[#84818c]">{lead.company || "Sin empresa"}</span></button></td><td className="px-5 py-4 text-xs text-[#696673]"><div>{lead.phone}</div><div>{lead.email || "—"}</div></td><td className="px-5 py-4">{lead.service?.name || "—"}</td><td className="px-5 py-4"><select aria-label={`Estado de ${lead.name}`} value={lead.status} onChange={e => quickStatus(lead.id, e.target.value)} className={`rounded-full border-0 px-2.5 py-1 text-xs font-semibold outline-none ring-1 ring-inset ${STATUS_STYLES[lead.status] || STATUS_STYLES.Nuevo}`}>{LEAD_STATUSES.map(s => <option key={s}>{s}</option>)}</select></td><td className="px-5 py-4">{lead.budget ? money(lead.budget) : "—"}</td><td className="px-5 py-4 font-medium">{lead.estimatedValue ? money(lead.estimatedValue) : "—"}</td><td className="px-5 py-4 text-[#777481]">{shortDate(lead.updatedAt)}</td><td className="px-5 py-4"><div className="flex gap-1"><button aria-label="Editar" onClick={() => openEdit(lead)} className="rounded-lg p-2 text-[#777481] hover:bg-violet-50 hover:text-violet-700"><Pencil size={16}/></button><button aria-label="Eliminar" onClick={() => remove(lead.id)} className="rounded-lg p-2 text-[#777481] hover:bg-red-50 hover:text-red-600"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>{!filtered.length && <p className="p-10 text-center text-sm text-[#88848f]">No se encontraron prospectos.</p>}</section>
    {creating && <div className="fixed inset-0 z-50 grid place-items-center bg-[#171522]/45 p-4"><form onSubmit={save} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-[#faf9fc] p-6 shadow-2xl"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-semibold">{editing ? "Editar prospecto" : "Nuevo prospecto"}</h2><p className="mt-1 text-sm text-[#777481]">Información de contacto y comercial</p></div><button type="button" aria-label="Cerrar" onClick={() => setCreating(false)}><X size={20}/></button></div><div className="grid gap-4 sm:grid-cols-2">{[["name","Nombre *"],["phone","Teléfono *"],["company","Empresa"],["email","Email"]].map(([key,label]) => <label key={key} className="text-sm font-medium">{label}<input className={`${input} mt-1.5`} value={form[key]} onChange={e => setForm({...form,[key]:e.target.value})}/></label>)}<label className="text-sm font-medium">Servicio<select className={`${input} mt-1.5`} value={form.serviceId} onChange={e => setForm({...form,serviceId:e.target.value})}><option value="">Sin definir</option>{services.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-sm font-medium">Estado<select className={`${input} mt-1.5`} value={form.status} onChange={e => setForm({...form,status:e.target.value})}>{LEAD_STATUSES.map(s => <option key={s}>{s}</option>)}</select></label>{[["budget","Presupuesto ($)"],["estimatedValue","Valor estimado ($)"],["source","Origen"]].map(([key,label]) => <label key={key} className="text-sm font-medium">{label}<input type={key === "source" ? "text" : "number"} className={`${input} mt-1.5`} value={form[key]} onChange={e => setForm({...form,[key]:e.target.value})}/></label>)}</div><label className="mt-4 block text-sm font-medium">Notas<textarea rows={4} className={`${input} mt-1.5 resize-none`} value={form.notes} onChange={e => setForm({...form,notes:e.target.value})}/></label>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setCreating(false)} className="rounded-xl border border-[#dedbe6] bg-white px-4 py-2.5 text-sm">Cancelar</button><button className="rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-medium text-white">Guardar prospecto</button></div></form></div>}
    {viewing && <div className="fixed inset-0 z-50 flex justify-end bg-[#171522]/35"><aside className="h-full w-full max-w-xl overflow-y-auto bg-[#faf9fc] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-2xl font-bold">{viewing.name}</h2><p className="mt-1 text-[#777481]">{viewing.company || "Sin empresa"}</p></div><button aria-label="Cerrar" onClick={() => setViewing(null)}><X size={21}/></button></div><div className="mt-6 grid gap-3 rounded-2xl border border-[#e7e4eb] bg-white p-5 sm:grid-cols-2"><div className="flex gap-2 text-sm"><Phone size={16} className="text-violet-600"/>{viewing.phone}</div><div className="flex gap-2 text-sm"><Mail size={16} className="text-violet-600"/>{viewing.email || "Sin email"}</div><div className="flex gap-2 text-sm"><Building2 size={16} className="text-violet-600"/>{viewing.company || "Sin empresa"}</div><div className="flex gap-2 text-sm"><MessageCircle size={16} className="text-violet-600"/>{viewing.source || "Sin origen"}</div></div><Section title="Información comercial"><p>Servicio: <b>{viewing.service?.name || "Sin definir"}</b></p><p>Presupuesto: <b>{viewing.budget ? money(viewing.budget) : "Sin definir"}</b></p><p>Valor estimado: <b>{viewing.estimatedValue ? money(viewing.estimatedValue) : "Sin definir"}</b></p><p>Estado: <b>{viewing.status}</b></p></Section><Section title="Notas"><p>{viewing.notes || "Sin notas todavía."}</p></Section><Section title="Resumen IA"><p>{viewing.aiSummary || "Analiza este prospecto desde Conversaciones para generar un resumen."}</p></Section><Section title="Historial de conversación"><div className="space-y-3">{viewing.conversation?.messages.map(m => <div key={m.id} className="rounded-xl bg-[#f5f3fa] p-3"><span className="text-xs font-semibold uppercase text-violet-600">{m.role === "customer" ? "Cliente" : "Soul Studios"}</span><p className="mt-1">{m.content}</p></div>) || <p>Sin mensajes.</p>}</div></Section><div className="mt-6 flex gap-2"><button onClick={() => openEdit(viewing)} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-medium text-white">Editar</button><a href={`/conversations?lead=${viewing.id}`} className="rounded-xl border border-[#dedbe6] bg-white px-4 py-2.5 text-sm">Abrir conversación</a></div></aside></div>}
  </div>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-5 rounded-2xl border border-[#e7e4eb] bg-white p-5 text-sm leading-6 text-[#696673]"><h3 className="mb-3 font-semibold text-[#24212c]">{title}</h3>{children}</section>; }
