"use client";

import { Bot, Code2, Globe2, Pencil, Plus, ShoppingBag, Smartphone, Trash2, X } from "lucide-react";
import { useState } from "react";

type Service = { id: number; name: string; description: string; startingPrice: number | null; active: boolean };
const icons = [Globe2, Code2, ShoppingBag, Smartphone, Bot];
const input = "mt-1.5 w-full rounded-xl border border-[#dedbe6] bg-white px-3.5 py-2.5 text-sm outline-none focus:border-violet-500 focus:ring-3 focus:ring-violet-100";
const empty = { name: "", description: "", startingPrice: "", active: true };
const money = (value: number) => `Q${Math.round(value).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`;

export function ServicesManager({ initialServices }: { initialServices: Service[] }) {
  const [services, setServices] = useState(initialServices); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<Service | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  async function reload() { setServices(await fetch("/api/services").then(r => r.json())); }
  function create() { setEditing(null); setForm(empty); setOpen(true); setError(""); }
  function edit(s: Service) { setEditing(s); setForm({ name: s.name, description: s.description, startingPrice: s.startingPrice?.toString() || "", active: s.active }); setOpen(true); setError(""); }
  async function save(e: { preventDefault(): void }) { e.preventDefault(); const res = await fetch(editing ? `/api/services/${editing.id}` : "/api/services", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await res.json(); if (!res.ok) return setError(data.error); await reload(); setOpen(false); }
  async function remove(id: number) { if (!confirm("¿Eliminar este servicio? Los prospectos conservarán sus demás datos.")) return; const res = await fetch(`/api/services/${id}`, { method: "DELETE" }); if (!res.ok) alert((await res.json()).error); else await reload(); }
  return <div className="mx-auto max-w-[1400px]"><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-sm font-medium text-violet-600">Catálogo comercial</p><h1 className="text-3xl font-bold tracking-tight">Servicios</h1><p className="mt-2 text-sm text-[#777481]">La IA usa estos servicios y precios como contexto para recomendar soluciones.</p></div><button onClick={create} className="flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-medium text-white"><Plus size={17}/> Nuevo servicio</button></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{services.map((service, i) => { const Icon = icons[i % icons.length]; return <article key={service.id} className="rounded-2xl border border-[#e9e7ed] bg-white p-5 shadow-[0_4px_18px_rgba(32,29,53,.035)]"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-xl bg-violet-50 text-violet-600"><Icon size={21}/></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${service.active ? "bg-emerald-50 text-emerald-700" : "bg-gray-100 text-gray-500"}`}>{service.active ? "Activo" : "Inactivo"}</span></div><h2 className="mt-5 font-semibold">{service.name}</h2><p className="mt-2 min-h-10 text-sm leading-5 text-[#777481]">{service.description}</p><div className="mt-5 flex items-end justify-between border-t border-[#efedf3] pt-4"><div><span className="text-xs text-[#8c8993]">Precio desde</span><div className="text-lg font-bold">{service.startingPrice ? money(service.startingPrice) : "Cotización"}</div></div><div className="flex"><button aria-label="Editar" onClick={() => edit(service)} className="rounded-lg p-2 text-[#777481] hover:bg-violet-50 hover:text-violet-600"><Pencil size={16}/></button><button aria-label="Eliminar" onClick={() => remove(service.id)} className="rounded-lg p-2 text-[#777481] hover:bg-red-50 hover:text-red-600"><Trash2 size={16}/></button></div></div></article>; })}</section>
    {open && <div className="fixed inset-0 z-50 grid place-items-center bg-[#171522]/45 p-4"><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-[#faf9fc] p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h2 className="text-xl font-semibold">{editing ? "Editar servicio" : "Nuevo servicio"}</h2><button type="button" aria-label="Cerrar" onClick={() => setOpen(false)}><X size={20}/></button></div><label className="block text-sm font-medium">Nombre<input className={input} value={form.name} onChange={e => setForm({...form,name:e.target.value})}/></label><label className="mt-4 block text-sm font-medium">Descripción<textarea rows={4} className={`${input} resize-none`} value={form.description} onChange={e => setForm({...form,description:e.target.value})}/></label><label className="mt-4 block text-sm font-medium">Precio desde (Q)<input type="number" className={input} value={form.startingPrice} onChange={e => setForm({...form,startingPrice:e.target.value})}/></label><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={e => setForm({...form,active:e.target.checked})}/> Servicio activo</label>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-xl border border-[#dedbe6] bg-white px-4 py-2.5 text-sm">Cancelar</button><button className="rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-medium text-white">Guardar</button></div></form></div>}
  </div>;
}
